'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EVO.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0042_092_refresh_update_reload_sync_syncronization_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_0042_092_refresh_update_reload_sync_syncronization_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _678092_sign_add_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("678092-sign-add-16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _678110_sign_info_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("678110-sign-info-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _678110_sign_info_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("678110-sign-info-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _91__5_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("91 (5)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _Game_Controller_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_Game_Controller_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _Rack_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_Rack-256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Armchair() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Armchair", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arrow_down_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_down_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arrow_up_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_up_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Calendar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Calendar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Calendar16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Calendar16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property caution_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("caution_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property compose_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("compose-16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property compose_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("compose-64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property controller_xbox_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("controller_xbox_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property desktop_monitor_screen_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("desktop_monitor_screen_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;h6&gt; &lt;b&gt;&lt;font color=&quot;#255663&quot;&gt;Device&lt;/font&gt;&lt;/b&gt; {0} &lt;/h6&gt;&lt;h6&gt; &lt;b&gt;&lt;font color=&quot;#255663&quot;&gt;Type&lt;/font&gt;&lt;/b&gt; &lt;font color=&quot;#1F497D&quot; size=&quot;7&quot;&gt;{1}&lt;/font&gt; &lt;/h6&gt;&lt;h6&gt; &lt;b&gt;&lt;font color=&quot;#255663&quot;&gt;State&lt;/font&gt;&lt;/b&gt; {2} &lt;/h6&gt;.
        '''</summary>
        Friend ReadOnly Property DevicesPanelDeviceInfo() As String
            Get
                Return ResourceManager.GetString("DevicesPanelDeviceInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property discount_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("discount_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property discount_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("discount_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property good_ok_check_mark_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("good_ok_check_mark-16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;font color=&quot;#000000&quot;&gt;&lt;b&gt;Type&lt;/b&gt;&lt;/font&gt; :&lt;font color=&quot;#7F7F7F&quot;&gt; {0}&lt;/font&gt;&lt;br/&gt;
        '''
        '''______________________________________________&lt;br/&gt;
        '''&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;b&gt;Time&lt;/b&gt;&lt;br/&gt;
        '''&lt;b&gt;&lt;font color=&quot;#000000&quot;&gt;StartTime&lt;/font&gt;&lt;/b&gt; :&lt;font color=&quot;#00B7EF&quot;&gt; {1}&lt;/font&gt;&lt;br/&gt;
        '''&lt;b&gt;&lt;font color=&quot;#000000&quot;&gt;Duration&lt;/font&gt;&lt;/b&gt; : &lt;font color=&quot;#00B7EF&quot;&gt;{2}&lt;/font&gt;  &lt;br/&gt;
        '''______________________________________________&lt;br/&gt;
        '''&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;b&gt;Bill&lt;/ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property HTMLDeviceInfo() As String
            Get
                Return ResourceManager.GetString("HTMLDeviceInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_set_azul() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_set_azul", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property justagain_din() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("justagain_din", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mdiClient1_BackgroundImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mdiClient1.BackgroundImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ______________________________________________&lt;br/&gt;
        '''&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;b&gt;OverTime&lt;/b&gt;&lt;br/&gt;
        '''&lt;b&gt;&lt;font color=&quot;#000000&quot;&gt;OverTimeBy&lt;/font&gt;&lt;/b&gt; :&lt;font color=&quot;#00B7EF&quot;&gt; {0}&lt;/font&gt;&lt;br/&gt;
        '''&lt;b&gt;&lt;font color=&quot;#000000&quot;&gt;OverTimeBill &lt;/font&gt;&lt;/b&gt; : &lt;font color=&quot;#00B7EF&quot;&gt;&lt;font color=&quot;#7F7F7F&quot;&gt; {1}&lt;/font&gt; &lt;font color=&quot;#F59D56&quot;&gt;&lt;b&gt; EGP&lt;/b&gt;&lt;/font&gt;&lt;/font&gt;  &lt;br/&gt;
        '''&lt;b&gt;&lt;font color=&quot;#000000&quot;&gt;TotalBill + OverTimeBill &lt;/font&gt;&lt;/b&gt; : &lt;font color=&quot;#00B7EF&quot;&gt;&lt;font color=&quot;#7F7F7F&quot;&gt; {2}&lt;/font&gt; &lt;font [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property OverTimeHTML() As String
            Get
                Return ResourceManager.GetString("OverTimeHTML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pencil_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pencil-16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property power_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("power_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PS4_Controller() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PS4_Controller", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property select_all_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("select_all_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Strange_Noise_SoundBible_com_229408508() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Strange_Noise_SoundBible_com_229408508", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tick_yes_approve_accept_green_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tick_yes_approve_accept_green_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property time_clock_history_recent_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("time_clock_history_recent_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UntitledGray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UntitledGray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UntitledWhite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UntitledWhite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x_cross_delete_stop_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x_cross_delete_stop_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
